name = "ESDLPlots"
uuid = "d555b242-3f29-57aa-84ea-3df92a135dfd"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ESDL = "359177bc-a543-11e8-11b7-bb015dba3358"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
StatPlots = "60ddc479-9b66-56df-82fc-76a74619b69c"
